CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_currency VARCHAR(3) NOT NULL DEFAULT 'IDR',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
